#!/bin/bash

################################################################################
# Anyline .NET SDK - License Key Generator
################################################################################
# This script generates a C# file containing the Anyline license key from
# the ANYLINE_MOBILE_SDK_LICENSE_KEY environment variable.
#
# Usage:
#   ./scripts/generate_license_key.sh           # Generate LicenseKey.cs
#   ./scripts/generate_license_key.sh --check   # Check if key is set (no generation)
#   ./scripts/generate_license_key.sh --help    # Show help
#
# The generated file is gitignored and must be created locally or in CI/CD.
################################################################################

set -e

# Find repository root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Output file location
OUTPUT_FILE="$REPO_ROOT/MAUI/LicenseKey.cs"

# Color codes (disabled if not a terminal)
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    RESET='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    RESET=''
fi

print_success() {
    echo -e "${GREEN}[OK]${RESET} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${RESET} $1" >&2
}

print_warning() {
    echo -e "${YELLOW}[WARN]${RESET} $1"
}

show_help() {
    cat << EOF
Anyline .NET SDK - License Key Generator

Usage:
  ./scripts/generate_license_key.sh           # Generate LicenseKey.cs
  ./scripts/generate_license_key.sh --check   # Check if key is set (no generation)
  ./scripts/generate_license_key.sh --help    # Show this help

Environment Variable:
  ANYLINE_MOBILE_SDK_LICENSE_KEY    Your Anyline license key (base64 encoded)

Output:
  MAUI/LicenseKey.cs       Generated C# file with license key

The generated file is gitignored and must be created:
  - Locally: Set env var and run this script before building
  - CI/CD: Pipeline generates file from GitLab CI variable
EOF
    exit 0
}

check_only() {
    if [[ -z "${ANYLINE_MOBILE_SDK_LICENSE_KEY:-}" ]]; then
        print_error "ANYLINE_MOBILE_SDK_LICENSE_KEY environment variable is not set"
        echo ""
        echo "To set the license key:"
        echo "  export ANYLINE_MOBILE_SDK_LICENSE_KEY=\"your-license-key-here\""
        echo ""
        echo "Add this to your shell profile (~/.zshrc or ~/.bashrc) for persistence."
        exit 1
    else
        print_success "ANYLINE_MOBILE_SDK_LICENSE_KEY is set"
        # Show first and last few characters for verification
        KEY_PREVIEW="${ANYLINE_MOBILE_SDK_LICENSE_KEY:0:20}...${ANYLINE_MOBILE_SDK_LICENSE_KEY: -10}"
        echo "  Key preview: $KEY_PREVIEW"
        exit 0
    fi
}

generate_license_key() {
    if [[ -z "${ANYLINE_MOBILE_SDK_LICENSE_KEY:-}" ]]; then
        print_error "ANYLINE_MOBILE_SDK_LICENSE_KEY environment variable is not set"
        echo ""
        echo "Cannot generate LicenseKey.cs without the license key."
        echo ""
        echo "To set the license key:"
        echo "  export ANYLINE_MOBILE_SDK_LICENSE_KEY=\"your-license-key-here\""
        echo ""
        echo "Add this to your shell profile (~/.zshrc or ~/.bashrc) for persistence."
        exit 1
    fi

    # Create the output directory if it doesn't exist
    mkdir -p "$(dirname "$OUTPUT_FILE")"

    # Generate the C# file
    cat > "$OUTPUT_FILE" << EOF
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate_license_key.sh from ANYLINE_MOBILE_SDK_LICENSE_KEY environment variable.
// This file is gitignored and must be regenerated locally or in CI/CD.

namespace Anyline.Examples.MAUI;

/// <summary>
/// Contains the Anyline SDK license key.
/// This file is auto-generated from the ANYLINE_MOBILE_SDK_LICENSE_KEY environment variable.
/// </summary>
public static class LicenseKey
{
    /// <summary>
    /// The Anyline SDK license key (base64 encoded).
    /// </summary>
    public static readonly string Value = "${ANYLINE_MOBILE_SDK_LICENSE_KEY}";
}
EOF

    print_success "Generated $OUTPUT_FILE"
}

# Parse arguments
case "${1:-}" in
    --help|-h)
        show_help
        ;;
    --check)
        check_only
        ;;
    *)
        generate_license_key
        ;;
esac
